### ISSUE TITLE
Presentation, Video or annotations ?

### ISSUE THREAD

**Issue by raDiesle** [mgechev/light-angularjs#1]
Hi,

great project! I would be interested in speech / explanation of slides and code + comments.

**Comment by mgechev** [comment]
Hi! Here are [some slided](https://speakerdeck.com/mgechev/lightweight-angularjs). I will write a blog post on this topic next weeks.

**Comment by mgechev** [comment]
@raDiesle [here is also a draft](https://github.com/mgechev/blog.mgechev.com/blob/f16c8ace0f95b71e97e3681af2a33c14dc9bdcb7/_drafts/build-learn-your-own-light-lightweight-angularjs.markdown) for a blog post I'm going to publish tomorrow (probably).
